# Form implementation generated from reading ui file 'designer/banUser.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 112)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupPassword = QtWidgets.QLineEdit(Dialog)
        self.groupPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.groupPassword.setObjectName("groupPassword")
        self.verticalLayout.addWidget(self.groupPassword)
        self.banButton = QtWidgets.QPushButton(Dialog)
        self.banButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.banButton.setObjectName("banButton")
        self.verticalLayout.addWidget(self.banButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.groupPassword, self.banButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Confirm group password"))
        self.groupPassword.setPlaceholderText(_translate("Dialog", "Password"))
        self.banButton.setText(_translate("Dialog", "Ban user"))
