# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/reset_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 112)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resetEmail = QtWidgets.QLineEdit(Dialog)
        self.resetEmail.setObjectName("resetEmail")
        self.verticalLayout.addWidget(self.resetEmail)
        self.resetUsername = QtWidgets.QLineEdit(Dialog)
        self.resetUsername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.resetUsername.setObjectName("resetUsername")
        self.verticalLayout.addWidget(self.resetUsername)
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout.addWidget(self.resetButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reset password"))
        self.resetEmail.setPlaceholderText(_translate("Dialog", "Email address"))
        self.resetUsername.setPlaceholderText(_translate("Dialog", "Username"))
        self.resetButton.setText(_translate("Dialog", "Send email to reset password"))
